# Feature Encoding

Feature encoding is the process of transforming categorical features into numeric. This is necessary because Ml algorithms can nly handle numeric features.

- Label Encoding
- One Hot Encoding
- Ordinal Encoding
- Binary Encoding

In [1]:
# import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
# Load dataset
df=sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [10]:
# Lets  encode the time with label encoder using sk learn

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
df['encoded_time']=le.fit_transform(df['time'])
df

     total_bill   tip     sex smoker   day    time  size  encoded_time
0         16.99  1.01  Female     No   Sun  Dinner     2             0
1         10.34  1.66    Male     No   Sun  Dinner     3             0
2         21.01  3.50    Male     No   Sun  Dinner     3             0
3         23.68  3.31    Male     No   Sun  Dinner     2             0
4         24.59  3.61  Female     No   Sun  Dinner     4             0
..          ...   ...     ...    ...   ...     ...   ...           ...
239       29.03  5.92    Male     No   Sat  Dinner     3             0
240       27.18  2.00  Female    Yes   Sat  Dinner     2             0
241       22.67  2.00    Male    Yes   Sat  Dinner     2             0
242       17.82  1.75    Male     No   Sat  Dinner     2             0
243       18.78  3.00  Female     No  Thur  Dinner     2             0

[244 rows x 8 columns]

In [15]:
print("Time values before Encoded",df['time'].value_counts())



print("_____________________________________________________")


print("Time values After Encoded",df['encoded_time'].value_counts())

Time values before Encoded time
Dinner    176
Lunch      68
Name: count, dtype: int64
_____________________________________________________
Time values After Encoded encoded_time
0    176
1     68
Name: count, dtype: int64

In [ ]:
# Ordinal encoding of days 

from sklearn.preprocessing import OrdinalEncoder

Oe=OrdinalEncoder(categories=[['Thur','Fri','Sat','Sun']])
df['Encoded_days']=Oe.fit_transform(df[['day']])

In [25]:
print("The values before encded",df['day'].value_counts())



print("The days after encoded",df['Encoded_days'].value_counts())

The values before encded day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64
The days after encoded Encoded_days
2.0    87
3.0    76
0.0    62
1.0    19
Name: count, dtype: int64

In [30]:
# One Hot Encoding on day column
from sklearn.preprocessing import OneHotEncoder
Oh=OneHotEncoder()

Oh.fit_transform(df[['smoker']]).toarray()

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [ ]:
#pip install category encoders
#from catgeor encders import target encoder

In [32]:
# Using Pandas for feature encoding

df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [33]:
# Pandas get dummies

pd.get_dummies(df['day'])

      Thur    Fri    Sat    Sun
0    False  False  False   True
1    False  False  False   True
2    False  False  False   True
3    False  False  False   True
4    False  False  False   True
..     ...    ...    ...    ...
239  False  False   True  False
240  False  False   True  False
241  False  False   True  False
242  False  False   True  False
243   True  False  False  False

[244 rows x 4 columns]

In [34]:
get_dummies=pd.get_dummies(df,columns=['day'])
get_dummies

,total_bill,tip,sex,smoker,time,size,day_Thur,day_Fri,day_Sat,day_Sun
0,16.99,1.01,Female,No,Dinner,2,False,False,False,True
1,10.34,1.66,Male,No,Dinner,3,False,False,False,True
2,21.01,3.50,Male,No,Dinner,3,False,False,False,True
3,23.68,3.31,Male,No,Dinner,2,False,False,False,True
4,24.59,3.61,Female,No,Dinner,4,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Dinner,3,False,False,True,False
240,27.18,2.00,Female,Yes,Dinner,2,False,False,True,False
241,22.67,2.00,Male,Yes,Dinner,2,False,False,True,False
242,17.82,1.75,Male,No,Dinner,2,False,False,True,False
243,18.78,3.00,Female,No,Dinner,2,True,False,False,False